version: "3.9"

services:
  app:
    build:
      context: .
    ports:
    #local port to docker port
      - "8000:8000"
    volumes:
    #map local app dir to docker app dir
      - ./app:/app
    command: >
      /bin/sh -c 'python manage.py runserver 0.0.0.0:8000' 
    #navigate to http://127.0.0.1:8000/ in your browser
      